import Navbar from '@/components/navbar'
import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
        <div>
        <Navbar />
        </div>
        <div>
          <div className='w-full p-3 flex items-center justify-center font-medium text-base text-slate-500 border-b border-slate-100'>
            Console administrateur I3DE
          </div>
          {children}
        </div>
        </body>
    </html>
  )
}
